[project]
name = 'AdChain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ad-placement]
path = 'contracts/ad-placement.clar'
clarity_version = 2
epoch = 2.5

[contracts.ad-token]
path = 'contracts/ad-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.user-data]
path = 'contracts/user-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
